FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Flask

## Ressources

### Generate Random Value [/val]

Cette ressource permet de générer un nombre aléatoire entre 1 et 100.

+ Parameters
    + random_val (optional, number, `1` to `100`) - Valeur aléatoire à générer.

#### GET

+ Response 200 (text/plain)

    Retourne le chiffre généré.

#### POST

+ Request (application/json)

    + Body

          {
              "random_val": 50
          }

+ Response 200 (text/plain)

    Retourne le chiffre généré.


### Adddition [/calc/add{?n1,n2}]

Cette ressource permet de réaliser une addition de deux nombres.

+ Parameters
  + n1 (number) - Le premier nombre.
  + n2 (number) - Le deuxième nombre.

#### GET

+ Response 200 (text/plain)

    Retourne le résultat de l'addition.
    
### Multiplication [/calc/prod{?n1,n2}]

Cette ressource permet de réaliser une multiplication de deux nombres.

+ Parameters
  + n1 (number) - Le premier nombre.
  + n2 (number) - Le deuxième nombre.

#### GET

+ Response 200 (text/plain)

    Retourne le résultat de la multiplication.
### Get Image [/img{?num}]

Cette ressource permet de récupérer une image à partir d'un numéro spécifié.

+ Parameters
  + num (number) - Le numéro de l'image (entre 1 et 9).

#### GET

+ Response 200 (image/png)

    Retourne l'image spécifiée par le numéro.

+ Response 400 (text/plain)

    Indique un numéro d'image invalide.

### Get Station Info [/stations_velo{?id}]

Cette ressource permet d'obtenir les informations sur une station de vélo en libre-service.

+ Parameters
  + id (string) - L'identifiant de la station.

#### GET

+ Response 200 (application/json)

    Retourne les informations de la station spécifiée.

+ Response 404 (application/json)

    Indique que la station n'a pas été trouvée.

